# Generated by Django 5.2.7 on 2025-10-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_cart_cart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_item',
            old_name='quentity',
            new_name='quantity',
        ),
    ]
