# Generated by Django 5.2.7 on 2025-10-15 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_ratings', models.PositiveBigIntegerField(default=0.0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='Api.product')),
            ],
        ),
    ]
